<?php

declare(strict_types=1);

namespace Aceextension\ImageOptmizer\Plugin\Frontend;

use Magento\Catalog\Model\Product\Image;
use Aceextension\ImageOptmizer\Helper\Data as ImageHelper;

class ProductImagePlugin
{
    /**
     * @param ImageHelper $imageHelper
     */
    public function __construct(
        private readonly ImageHelper $imageHelper
    ) {}

    /**
     * Prevent Magento from spending time generating physical image files during HTML generation.
     * The file will be requested by the browser, intercepted by Nginx, and dynamically generated
     * on the fly via pub/get.php and our WebP Go proxy.
     *
     * @param Image $subject
     * @param \Closure $proceed
     * @return Image
     */
    public function aroundSaveFile(Image $subject, \Closure $proceed): Image
    {
        if ($this->imageHelper->isMaterializationMode()) {
            return $proceed();
        }

        if (!$this->imageHelper->isWebpReplacementEnabled()) {
            return $proceed();
        }

        // Bypass the default image save logic to drastically speed up frontend rendering.
        // The image will be dynamically generated by pub/get.php when requested.
        return $subject;
    }
}
